/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as ApiSplatRouteImport } from './routes/api.$'
import { Route as AppLibraryRouteImport } from './routes/_app/_library'
import { Route as AppLibraryFilesRouteImport } from './routes/_app/_library/files'
import { Route as AppLibraryDocumentsDocumentIdRouteImport } from './routes/_app/_library/documents.$documentId'
import { Route as AppLibraryDecksDeckIdRouteImport } from './routes/_app/_library/decks.$deckId'

const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppLibraryRoute = AppLibraryRouteImport.update({
  id: '/_library',
  getParentRoute: () => AppRoute,
} as any)
const AppLibraryFilesRoute = AppLibraryFilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => AppLibraryRoute,
} as any)
const AppLibraryDocumentsDocumentIdRoute =
  AppLibraryDocumentsDocumentIdRouteImport.update({
    id: '/documents/$documentId',
    path: '/documents/$documentId',
    getParentRoute: () => AppLibraryRoute,
  } as any)
const AppLibraryDecksDeckIdRoute = AppLibraryDecksDeckIdRouteImport.update({
  id: '/decks/$deckId',
  path: '/decks/$deckId',
  getParentRoute: () => AppLibraryRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/sign-in': typeof SignInRoute
  '/api/$': typeof ApiSplatRoute
  '/files': typeof AppLibraryFilesRoute
  '/decks/$deckId': typeof AppLibraryDecksDeckIdRoute
  '/documents/$documentId': typeof AppLibraryDocumentsDocumentIdRoute
}
export interface FileRoutesByTo {
  '/sign-in': typeof SignInRoute
  '/': typeof AppIndexRoute
  '/api/$': typeof ApiSplatRoute
  '/files': typeof AppLibraryFilesRoute
  '/decks/$deckId': typeof AppLibraryDecksDeckIdRoute
  '/documents/$documentId': typeof AppLibraryDocumentsDocumentIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/_app/_library': typeof AppLibraryRouteWithChildren
  '/api/$': typeof ApiSplatRoute
  '/_app/': typeof AppIndexRoute
  '/_app/_library/files': typeof AppLibraryFilesRoute
  '/_app/_library/decks/$deckId': typeof AppLibraryDecksDeckIdRoute
  '/_app/_library/documents/$documentId': typeof AppLibraryDocumentsDocumentIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sign-in'
    | '/api/$'
    | '/files'
    | '/decks/$deckId'
    | '/documents/$documentId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/sign-in'
    | '/'
    | '/api/$'
    | '/files'
    | '/decks/$deckId'
    | '/documents/$documentId'
  id:
    | '__root__'
    | '/_app'
    | '/sign-in'
    | '/_app/_library'
    | '/api/$'
    | '/_app/'
    | '/_app/_library/files'
    | '/_app/_library/decks/$deckId'
    | '/_app/_library/documents/$documentId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  SignInRoute: typeof SignInRoute
  ApiSplatRoute: typeof ApiSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/_library': {
      id: '/_app/_library'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppLibraryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/_library/files': {
      id: '/_app/_library/files'
      path: '/files'
      fullPath: '/files'
      preLoaderRoute: typeof AppLibraryFilesRouteImport
      parentRoute: typeof AppLibraryRoute
    }
    '/_app/_library/documents/$documentId': {
      id: '/_app/_library/documents/$documentId'
      path: '/documents/$documentId'
      fullPath: '/documents/$documentId'
      preLoaderRoute: typeof AppLibraryDocumentsDocumentIdRouteImport
      parentRoute: typeof AppLibraryRoute
    }
    '/_app/_library/decks/$deckId': {
      id: '/_app/_library/decks/$deckId'
      path: '/decks/$deckId'
      fullPath: '/decks/$deckId'
      preLoaderRoute: typeof AppLibraryDecksDeckIdRouteImport
      parentRoute: typeof AppLibraryRoute
    }
  }
}

interface AppLibraryRouteChildren {
  AppLibraryFilesRoute: typeof AppLibraryFilesRoute
  AppLibraryDecksDeckIdRoute: typeof AppLibraryDecksDeckIdRoute
  AppLibraryDocumentsDocumentIdRoute: typeof AppLibraryDocumentsDocumentIdRoute
}

const AppLibraryRouteChildren: AppLibraryRouteChildren = {
  AppLibraryFilesRoute: AppLibraryFilesRoute,
  AppLibraryDecksDeckIdRoute: AppLibraryDecksDeckIdRoute,
  AppLibraryDocumentsDocumentIdRoute: AppLibraryDocumentsDocumentIdRoute,
}

const AppLibraryRouteWithChildren = AppLibraryRoute._addFileChildren(
  AppLibraryRouteChildren,
)

interface AppRouteChildren {
  AppLibraryRoute: typeof AppLibraryRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppLibraryRoute: AppLibraryRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  SignInRoute: SignInRoute,
  ApiSplatRoute: ApiSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
